CREATE TABLE `USER_INFO` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(64) NOT NULL COMMENT '姓名',
	`AGE`	int(10) NOT NULL COMMENT'年龄',
	`PWD` varchar(12) NOT NULL COMMENT '密码',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin comment '用户表';
